import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import Toolbar from "@/components/toolbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <Toolbar />
        {children}
      </body>
    </html>
  );
}
